name: DockerHub CI

on:
  push:
    tags:
      - '*/*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Parse Tag Name
        uses: jungwinter/split@v2
        id: split
        with:
          msg: ${{ github.ref }}
          separator: '/'

      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: startsWith( github.ref, 'refs/tags/')
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        if: startsWith( github.ref, 'refs/tags/')
        with:
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          context: ./${{ steps.split.outputs._0 }}
          file: ./Dockerfile
          tags: ossyupiik/${{ steps.split.outputs._2 }}:${{ steps.split.outputs._3 }}
          labels: |
            org.opencontainers.image.vendor=Yupiik

      - name: Image Report
        run: echo ossyupiik/${{ steps.split.outputs._0 }}:${{ steps.split.outputs._1 }}@${{ steps.docker_build.outputs.digest }}
