name: DockerHub CI

on:
  push:
    tags:
      - '*/*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Parsed tag
        id: parsed_tag
        run: |
          ref=${{ github.ref }}
          info_by_line=$(echo "$ref" | tr '/' '\n')
          version=$(echo "$info_by_line" | tail -n 1)
          image=$(echo "$info_by_line" | tail -n 2 | head -n 1)
          echo "::set-output name=image::$image"
          echo "::set-output name=version::$version"
          echo "Image=$image,Version=$version"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: startsWith( github.ref, 'refs/tags/')
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        if: startsWith( github.ref, 'refs/tags/')
        with:
          push: true
          context: ./${{ steps.parsed_tag.outputs.image }}
          file: ./${{ steps.parsed_tag.outputs.image }}/Dockerfile
          tags: ossyupiik/${{ steps.parsed_tag.outputs.image }}:${{ steps.parsed_tag.outputs.version }}
          labels: |
            org.opencontainers.image.vendor=Yupiik

      - name: Image Report
        run: echo ossyupiik/${{ steps.parsed_tag.outputs.image }}:${{ steps.parsed_tag.outputs.version }}@${{ steps.docker_build.outputs.digest }}
